### **Playground**

In [2]:
import torch

# Simulating logits tensor (batch_size=2, seq_len=4, vocab_size=5)
logits = torch.tensor([
    [[1.0, 2.0, 3.0, 4.0, 5.0],   # Token 1 in batch 1
     [2.0, 3.0, 4.0, 5.0, 6.0],   # Token 2 in batch 1
     [3.0, 4.0, 5.0, 6.0, 7.0],   # Token 3 in batch 1
     [4.0, 5.0, 6.0, 7.0, 8.0]],  # Token 4 (last token) in batch 1

    [[1.5, 2.5, 3.5, 4.5, 5.5],   # Token 1 in batch 2
     [2.5, 3.5, 4.5, 5.5, 6.5],   # Token 2 in batch 2
     [3.5, 4.5, 5.5, 6.5, 7.5],   # Token 3 in batch 2
     [4.5, 5.5, 6.5, 7.5, 8.5]]   # Token 4 (last token) in batch 2
])

temperature = 1.0  # No scaling effect for simplicity

# Select logits of the last token in each batch
last_token_logits = logits[:, -1]  # Shape: (batch_size=2, vocab_size=5)
print(last_token_logits)

tensor([[4.0000, 5.0000, 6.0000, 7.0000, 8.0000],
        [4.5000, 5.5000, 6.5000, 7.5000, 8.5000]])


In [3]:
# Apply softmax
probs = torch.softmax(last_token_logits / temperature, dim=-1)

# Print results
print("Logits of last tokens for each batch:")
print(last_token_logits)

print("\nSoftmax probabilities:")
print(probs)

Logits of last tokens for each batch:
tensor([[4.0000, 5.0000, 6.0000, 7.0000, 8.0000],
        [4.5000, 5.5000, 6.5000, 7.5000, 8.5000]])

Softmax probabilities:
tensor([[0.0117, 0.0317, 0.0861, 0.2341, 0.6364],
        [0.0117, 0.0317, 0.0861, 0.2341, 0.6364]])
